version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db_container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    
  # node api service
  api:
    build: .
    container_name: nodejs_container
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - mongo

volumes:
  mongo: {}